name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Run release checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.0"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with: 
          version: 7.14.0
      - name: Install packages
        run: pnpm i
      - name: Create release and publish to npm
        id: changesets
        uses: changesets/action@v1
        with: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          NPM_TOKEN: ${{ secrets.N_TOKEN }}
